// ============================================================
// CodeMorph AI Engine — ZIP Packager
// PHASE 8: Packaging propre du résultat de conversion
//
// Objectif:
//   - Créer un output.zip directement exploitable
//   - Aucun commentaire LLM parasite
//   - Aucune balise ``` résiduelle
//   - Aucun placeholder "Replace this..."
//   - Aucune note explicative dans le code
//   - Structure de projet propre et cohérente
// ============================================================

import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { exec } from 'child_process';
import { promisify } from 'util';
import type { GeneratedFile } from '../models/ir.types';

const execAsync = promisify(exec);

// ── Types ──────────────────────────────────────────────────────────────────

export interface ZipPackageResult {
  success:      boolean;
  zipPath:      string;     // chemin absolu vers le ZIP créé
  zipBuffer?:   Buffer | undefined;     // contenu binaire du ZIP
  fileCount:    number;
  totalBytes:   number;
  error?:       string | undefined;
  duration:     number;
}

// ── Nettoyage Phase 8: suppression artefacts LLM résiduels ───────────────

/**
 * Nettoie le contenu d'un fichier pour le ZIP final:
 * - Supprime les fences ``` résiduelles
 * - Supprime les commentaires LLM
 * - Supprime les TODO générés par le pipeline
 * - Supprime les placeholders
 */
export function cleanForPackaging(content: string, filePath: string): string {
  const ext = filePath.split('.').pop()?.toLowerCase() ?? '';

  // Pas de nettoyage pour les fichiers non-code
  if (['json', 'yaml', 'yml', 'md', 'txt', 'png', 'jpg', 'svg', 'ico', 'env'].includes(ext)) {
    // Pour YAML/JSON: juste supprimer les fences éventuelles
    if (['json', 'yaml', 'yml'].includes(ext)) {
      return content.replace(/^```[a-zA-Z]*\n?/gm, '').replace(/\n```$/gm, '').trim() + '\n';
    }
    return content;
  }

  let cleaned = content;

  // 1. Supprimer les fences markdown résiduelles
  cleaned = cleaned.replace(/^```[a-zA-Z0-9]*\s*$/gm, '');
  cleaned = cleaned.replace(/^```\s*$/gm, '');

  // 2. Supprimer les commentaires LLM typiques
  const LLM_COMMENT_PATTERNS = [
    /^\s*\/\/ TODO\(codeMorph\): .+? — implement based on source logic\s*$/gm,
    /^\s*\/\/ MISSING IMPORT: .+$/gm,
    /^\s*\/\/ REMOVED unused import:.+$/gm,
    /^\s*\/\/ TODO: missing import .+$/gm,
    /^\s*\/\/ NOTE: .+generated by CodeMorph.+$/gm,
    /^\s*\/\*\s*Note:.+?\*\/\s*$/gms,
    /^\s*\/\/ Replace this with (?:your|the|actual).+$/gim,
    /^\s*\/\/ Add (?:your|the) (?:actual|real) (?:content|logic|code|implementation) here\s*$/gim,
    /^\s*\/\/ Example (?:implementation|usage|code)[:\s]*$/gim,
    /^\s*\/\/ (?:Dart|Flutter) code for .*$/gim,
    // Dart comment patterns
    /^\s*\/\/ TODO: (?:Replace|Add|Update|Modify|Configure|Implement) (?:with|your|the|this).+$/gim,
    /^\s*\/\/ auto-generated by CodeMorph.*$/gim,
  ];

  for (const pattern of LLM_COMMENT_PATTERNS) {
    cleaned = cleaned.replace(pattern, '');
  }

  // 3. Supprimer les lignes de placeholder
  const PLACEHOLDER_PATTERNS = [
    /^\s*\/\/ your implementation here\s*$/gim,
    /^\s*\/\/ implement this\s*$/gim,
    /^\s*throw UnimplementedError\(\);\s*\/\/ TODO: implement$/gim,
    /^\s*print\('TODO: implement.*'\);\s*$/gim,
  ];

  for (const pattern of PLACEHOLDER_PATTERNS) {
    cleaned = cleaned.replace(pattern, '');
  }

  // 4. Normaliser les lignes vides excessives
  cleaned = cleaned.replace(/\n{4,}/g, '\n\n\n');

  // 5. Trim final
  cleaned = cleaned.trim();
  if (cleaned && !cleaned.endsWith('\n')) cleaned += '\n';

  return cleaned;
}

// ── Créer la structure des dossiers ──────────────────────────────────────

function ensureDirSync(dirPath: string): void {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

// ── Écrire les fichiers dans un dossier ──────────────────────────────────

function writeFilesToDir(files: GeneratedFile[], baseDir: string): void {
  for (const file of files) {
    if (!file.content) continue;

    // Nettoyage Phase 8
    const cleanedContent = cleanForPackaging(file.content, file.path);

    const fullPath = path.join(baseDir, file.path);
    const fileDir  = path.dirname(fullPath);
    ensureDirSync(fileDir);
    fs.writeFileSync(fullPath, cleanedContent, 'utf8');
  }
}

// ── Créer le ZIP avec la commande zip (disponible sur Linux/macOS) ────────

async function createZipFromDir(sourceDir: string, outputPath: string): Promise<boolean> {
  try {
    await execAsync(`cd "${sourceDir}" && zip -r "${outputPath}" . -x "*.DS_Store" -x "__MACOSX/*"`, {
      timeout: 30000,
    });
    return true;
  } catch (err) {
    console.warn(`[ZipPackager] zip command failed: ${(err as Error).message}`);
    return false;
  }
}

// ── Créer le ZIP en JavaScript pur (fallback si zip non disponible) ────────

async function createZipInMemory(files: GeneratedFile[]): Promise<Buffer> {
  // Implémentation ZIP minimaliste sans dépendance externe
  // Format ZIP selon PKZIP spec (Local File Header + Central Directory)
  const entries: Array<{ name: string; data: Buffer; crc32: number }> = [];

  function crc32(buf: Buffer): number {
    const table = new Uint32Array(256);
    for (let i = 0; i < 256; i++) {
      let c = i;
      for (let k = 0; k < 8; k++) {
        c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1);
      }
      table[i] = c;
    }
    let crc = 0xFFFFFFFF;
    for (let i = 0; i < buf.length; i++) {
      crc = (crc >>> 8) ^ table[(crc ^ (buf[i] ?? 0)) & 0xFF]!;
    }
    return ((crc ^ 0xFFFFFFFF) >>> 0);
  }

  function writeUInt16LE(n: number): Buffer {
    const b = Buffer.alloc(2);
    b.writeUInt16LE(n, 0);
    return b;
  }
  function writeUInt32LE(n: number): Buffer {
    const b = Buffer.alloc(4);
    b.writeUInt32LE(n >>> 0, 0);
    return b;
  }

  const LOCAL_FILE_HEADER_SIG = 0x04034b50;
  const CENTRAL_DIR_SIG       = 0x02014b50;
  const END_CENTRAL_DIR_SIG   = 0x06054b50;

  for (const file of files) {
    if (!file.content) continue;
    const dataBytes = Buffer.from(cleanForPackaging(file.content, file.path), 'utf8');
    const checksum  = crc32(dataBytes);
    entries.push({ name: file.path, data: dataBytes, crc32: checksum });
  }

  // Build local file entries
  const localBlocks: Buffer[] = [];
  const offsets: number[] = [];
  let offset = 0;

  for (const entry of entries) {
    const nameBytes = Buffer.from(entry.name, 'utf8');
    offsets.push(offset);

    const header = Buffer.concat([
      writeUInt32LE(LOCAL_FILE_HEADER_SIG),  // signature
      writeUInt16LE(20),                     // version needed
      writeUInt16LE(0),                      // flags
      writeUInt16LE(0),                      // compression (stored)
      writeUInt16LE(0),                      // last mod time
      writeUInt16LE(0),                      // last mod date
      writeUInt32LE(entry.crc32),            // crc32
      writeUInt32LE(entry.data.length),      // compressed size
      writeUInt32LE(entry.data.length),      // uncompressed size
      writeUInt16LE(nameBytes.length),       // filename length
      writeUInt16LE(0),                      // extra length
      nameBytes,
      entry.data,
    ]);

    localBlocks.push(header);
    offset += header.length;
  }

  // Build central directory
  const centralDirBlocks: Buffer[] = [];
  const centralDirOffset = offset;

  for (let i = 0; i < entries.length; i++) {
    const entry = entries[i]!;
    const nameBytes = Buffer.from(entry.name, 'utf8');

    centralDirBlocks.push(Buffer.concat([
      writeUInt32LE(CENTRAL_DIR_SIG),
      writeUInt16LE(20),             // version made by
      writeUInt16LE(20),             // version needed
      writeUInt16LE(0),              // flags
      writeUInt16LE(0),              // compression
      writeUInt16LE(0),              // last mod time
      writeUInt16LE(0),              // last mod date
      writeUInt32LE(entry.crc32),
      writeUInt32LE(entry.data.length),
      writeUInt32LE(entry.data.length),
      writeUInt16LE(nameBytes.length),
      writeUInt16LE(0),              // extra
      writeUInt16LE(0),              // comment
      writeUInt16LE(0),              // disk
      writeUInt16LE(0),              // internal attr
      writeUInt32LE(0),              // external attr
      writeUInt32LE(offsets[i]!),    // local header offset
      nameBytes,
    ]));
  }

  const centralDir = Buffer.concat(centralDirBlocks);

  // End of central directory
  const endRecord = Buffer.concat([
    writeUInt32LE(END_CENTRAL_DIR_SIG),
    writeUInt16LE(0),                       // disk number
    writeUInt16LE(0),                       // start disk
    writeUInt16LE(entries.length),          // entries on disk
    writeUInt16LE(entries.length),          // total entries
    writeUInt32LE(centralDir.length),       // central dir size
    writeUInt32LE(centralDirOffset),        // central dir offset
    writeUInt16LE(0),                       // comment length
  ]);

  return Buffer.concat([...localBlocks, centralDir, endRecord]);
}

// ── Fonction principale ───────────────────────────────────────────────────

export async function packageToZip(
  files:       GeneratedFile[],
  projectName: string = 'output',
  outputPath?: string,
): Promise<ZipPackageResult> {
  const startTime = Date.now();
  const zipName   = outputPath ?? path.join(os.tmpdir(), `${projectName}_output.zip`);

  try {
    console.log(`\n[ZipPackager] Packaging ${files.length} files → ${zipName}`);

    // Essayer avec la commande zip système
    const tmpProjectDir = path.join(os.tmpdir(), `codemorph_pkg_${Date.now()}`);
    ensureDirSync(tmpProjectDir);

    // Écrire les fichiers nettoyés
    writeFilesToDir(files, tmpProjectDir);

    const fileCount = files.filter((f) => !!f.content).length;
    let totalBytes  = 0;

    let zipCreated = false;

    // Essayer zip système
    try {
      await execAsync('which zip', { timeout: 3000 });
      zipCreated = await createZipFromDir(tmpProjectDir, zipName);
    } catch {
      zipCreated = false;
    }

    // Fallback: ZIP en mémoire
    let zipBuffer: Buffer | undefined;
    if (!zipCreated) {
      console.log(`[ZipPackager] Using in-memory ZIP builder`);
      zipBuffer = await createZipInMemory(files);
      fs.writeFileSync(zipName, zipBuffer);
      zipCreated = true;
    }

    if (fs.existsSync(zipName)) {
      totalBytes = fs.statSync(zipName).size;
    }

    // Cleanup temp dir
    try { fs.rmSync(tmpProjectDir, { recursive: true, force: true }); } catch { /* ignore */ }

    const duration = Date.now() - startTime;
    console.log(`[ZipPackager] ✅ ZIP created: ${zipName} (${fileCount} files, ${Math.round(totalBytes / 1024)}KB, ${duration}ms)`);

    return {
      success:    true,
      zipPath:    zipName,
      ...(zipBuffer !== undefined ? { zipBuffer } : {}),
      fileCount,
      totalBytes,
      duration,
    };

  } catch (err) {
    const duration = Date.now() - startTime;
    console.error(`[ZipPackager] ❌ ZIP creation failed: ${(err as Error).message}`);
    return {
      success:    false,
      zipPath:    zipName,
      fileCount:  0,
      totalBytes: 0,
      error:      (err as Error).message,
      duration,
    };
  }
}
