// ============================================================
// CodeMorph — Module declarations (workspace-resolved packages)
// ============================================================

// lucide-react is hoisted to workspace root — declare types here
// so TypeScript finds them without needing a local copy
declare module 'lucide-react' {
  import * as React from 'react';

  export interface IconProps extends React.SVGProps<SVGSVGElement> {
    size?: number | string;
    strokeWidth?: number | string;
    absoluteStrokeWidth?: boolean;
  }

  export type Icon = React.ForwardRefExoticComponent<
    IconProps & React.RefAttributes<SVGSVGElement>
  >;

  // ── Commonly used icons ───────────────────────────────────
  export const LayoutDashboard: Icon;
  export const FolderGit2: Icon;
  export const FolderTree: Icon;
  export const Zap: Icon;
  export const BarChart3: Icon;
  export const Settings: Icon;
  export const Users: Icon;
  export const CreditCard: Icon;
  export const HelpCircle: Icon;
  export const ChevronLeft: Icon;
  export const ChevronRight: Icon;
  export const Code2: Icon;
  export const Bell: Icon;
  export const Search: Icon;
  export const Sun: Icon;
  export const Moon: Icon;
  export const Command: Icon;
  export const ArrowUpRight: Icon;
  export const Plus: Icon;
  export const Clock: Icon;
  export const TrendingUp: Icon;
  export const CheckCircle2: Icon;
  export const AlertCircle: Icon;
  export const Loader2: Icon;
  export const Download: Icon;
  export const ExternalLink: Icon;
  export const Copy: Icon;
  export const Check: Icon;
  export const X: Icon;
  export const ChevronDown: Icon;
  export const ChevronUp: Icon;
  export const Info: Icon;
  export const Lock: Icon;
  export const Unlock: Icon;
  export const Shield: Icon;
  export const Star: Icon;
  export const Sparkles: Icon;
  export const Github: Icon;
  export const Globe: Icon;
  export const Mail: Icon;
  export const User: Icon;
  export const LogOut: Icon;
  export const Menu: Icon;
  export const MoreVertical: Icon;
  export const MoreHorizontal: Icon;
  export const Trash: Icon;
  export const Trash2: Icon;
  export const Edit: Icon;
  export const Edit2: Icon;
  export const Eye: Icon;
  export const EyeOff: Icon;
  export const RefreshCw: Icon;
  export const RotateCcw: Icon;
  export const Upload: Icon;
  export const File: Icon;
  export const FileCode: Icon;
  export const FileText: Icon;
  export const Folder: Icon;
  export const Link: Icon;
  export const Tag: Icon;
  export const Hash: Icon;
  export const Activity: Icon;
  export const Database: Icon;
  export const Server: Icon;
  export const Cpu: Icon;
  export const Gauge: Icon;
  export const Home: Icon;
  export const ArrowLeft: Icon;
  export const ArrowRight: Icon;
  export const PlayCircle: Icon;
  export const PauseCircle: Icon;
  export const StopCircle: Icon;
  export const Terminal: Icon;
  export const Code: Icon;
  export const Package: Icon;
  export const Boxes: Icon;
  export const Building: Icon;
  export const Building2: Icon;
  export const Wallet: Icon;
  export const Receipt: Icon;
  export const BarChart: Icon;
  export const PieChart: Icon;
  export const LineChart: Icon;
  export const FlaskConical: Icon;
  export const Microscope: Icon;
  export const Lightbulb: Icon;
  export const MessageSquare: Icon;
  export const MessageCircle: Icon;
  export const ThumbsUp: Icon;
  export const ThumbsDown: Icon;
  export const Heart: Icon;
  export const Bookmark: Icon;
  export const Share: Icon;
  export const Share2: Icon;
  export const Send: Icon;
  export const Filter: Icon;
  export const SortAsc: Icon;
  export const SortDesc: Icon;
  export const List: Icon;
  export const Grid: Icon;
  export const Grid3x3: Icon;
  export const LayoutGrid: Icon;
  export const Columns: Icon;
  export const Rows: Icon;
  export const Maximize: Icon;
  export const Minimize: Icon;
  export const Maximize2: Icon;
  export const Minimize2: Icon;
  export const ZoomIn: Icon;
  export const ZoomOut: Icon;
  export const Save: Icon;
  export const Key: Icon;
  export const KeyRound: Icon;
  export const Webhook: Icon;
  export const Workflow: Icon;
  export const GitBranch: Icon;
  export const GitCommit: Icon;
  export const GitMerge: Icon;
  export const GitPullRequest: Icon;
  export const Layers: Icon;
  export const Layout: Icon;
  export const Sidebar: Icon;
  export const PanelLeft: Icon;
  export const PanelRight: Icon;
  export const ScanLine: Icon;
  export const QrCode: Icon;
  export const Braces: Icon;
  export const Brackets: Icon;
  export const AlertTriangle: Icon;
  export const XCircle: Icon;
  export const CheckCircle: Icon;
  export const HelpCircle: Icon;
  export const Slash: Icon;
  export const Dot: Icon;
  export const Circle: Icon;
  export const Square: Icon;
  export const Triangle: Icon;
  export const Hexagon: Icon;
  export const Infinity: Icon;
  export const Rocket: Icon;
  export const Flame: Icon;
  export const Trophy: Icon;
  export const Crown: Icon;
  export const Diamond: Icon;
  export const Gem: Icon;
  export const Badge: Icon;
  export const BadgeCheck: Icon;
  export const BadgePlus: Icon;
  export const Percent: Icon;
  export const DollarSign: Icon;
  export const Euro: Icon;
  export const Clock3: Icon;
  export const Timer: Icon;
  export const CalendarDays: Icon;
  export const Calendar: Icon;
  export const MapPin: Icon;
  export const Navigation: Icon;
  export const LogIn: Icon;
  export const UserPlus: Icon;
  export const UserMinus: Icon;
  export const UserCheck: Icon;
  export const UsersRound: Icon;
  export const Pencil: Icon;
  export const Eraser: Icon;
  export const Clipboard: Icon;
  export const ClipboardCheck: Icon;
  export const ClipboardList: Icon;
  export const Image: Icon;
  export const ImageOff: Icon;
  export const Video: Icon;
  export const Music: Icon;
  export const Headphones: Icon;
  export const Mic: Icon;
  export const Volume: Icon;
  export const Volume2: Icon;
  export const VolumeX: Icon;
  export const Wifi: Icon;
  export const WifiOff: Icon;
  export const Bluetooth: Icon;
  export const Battery: Icon;
  export const BatteryCharging: Icon;
  export const Power: Icon;
  export const PowerOff: Icon;
  export const Monitor: Icon;
  export const Laptop: Icon;
  export const Smartphone: Icon;
  export const Tablet: Icon;
  export const Printer: Icon;
  export const Scanner: Icon;
  export const HardDrive: Icon;
  export const MemoryStick: Icon;
  export const CloudUpload: Icon;
  export const CloudDownload: Icon;
  export const Cloud: Icon;
  export const CloudOff: Icon;

  // Allow any other icon from lucide-react
  const icons: { [key: string]: Icon };
  export default icons;
}
